"""returned back DateTime field to Offer

Revision ID: aae3fa4873cf
Revises: 8fc95b086c13
Create Date: 2020-11-13 19:39:52.869574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae3fa4873cf'
down_revision = '8fc95b086c13'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
