"""create main tables: point, user, goods, offers

Revision ID: 288fd0342b63
Revises: 
Create Date: 2020-10-27 00:02:35.933196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288fd0342b63'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods')),
    sa.UniqueConstraint('name', name=op.f('uq_goods_name'))
    )
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('offers',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.Column('type_offer', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('incoterms', sa.String(length=5), nullable=False),
    sa.Column('calorific', sa.Numeric(), nullable=True),
    sa.Column('ash', sa.Numeric(), nullable=True),
    sa.Column('humidity', sa.Numeric(), nullable=True),
    sa.Column('sulfur', sa.Numeric(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], name=op.f('fk_offers_goods_id_goods')),
    sa.ForeignKeyConstraint(['point_id'], ['point.id'], name=op.f('fk_offers_point_id_point')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_offers_user_id_user')),
    sa.PrimaryKeyConstraint('offer_id', name=op.f('pk_offers'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    op.drop_table('user')
    op.drop_table('point')
    op.drop_table('goods')
    # ### end Alembic commands ###
