"""modified creation_date in offer

Revision ID: 8fc95b086c13
Revises: 9841092249d2
Create Date: 2020-11-12 19:51:04.787825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc95b086c13'
down_revision = '9841092249d2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
