"""added new techical params to offer

Revision ID: 9beaef61c5b6
Revises: 24ac4750332c
Create Date: 2020-11-08 19:30:13.629740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9beaef61c5b6'
down_revision = '24ac4750332c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('arsenic_content', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('ash_content', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('ash_melting_temp', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('bulk_density', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('cadmium_content', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('chlorine_content', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('chromium_content', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('copper_content', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('diameter', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('fines', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('lead_content', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('length_min', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('lenngth_max', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('mechanical_durability', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('mercury_content', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('moisture_content', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('net_calorific_value', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('nickel_content', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('nitrogen_content', sa.Numeric(), nullable=True))
    op.add_column('offer', sa.Column('sulphur_content', sa.Numeric(), nullable=True))
    op.alter_column('offer', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('offer', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('offer', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('offer', 'sulphur_content')
    op.drop_column('offer', 'nitrogen_content')
    op.drop_column('offer', 'nickel_content')
    op.drop_column('offer', 'net_calorific_value')
    op.drop_column('offer', 'moisture_content')
    op.drop_column('offer', 'mercury_content')
    op.drop_column('offer', 'mechanical_durability')
    op.drop_column('offer', 'lenngth_max')
    op.drop_column('offer', 'length_min')
    op.drop_column('offer', 'lead_content')
    op.drop_column('offer', 'fines')
    op.drop_column('offer', 'diameter')
    op.drop_column('offer', 'copper_content')
    op.drop_column('offer', 'chromium_content')
    op.drop_column('offer', 'chlorine_content')
    op.drop_column('offer', 'cadmium_content')
    op.drop_column('offer', 'bulk_density')
    op.drop_column('offer', 'ash_melting_temp')
    op.drop_column('offer', 'ash_content')
    op.drop_column('offer', 'arsenic_content')
    # ### end Alembic commands ###
