"""init

Revision ID: 3c1b04d5af14
Revises: 
Create Date: 2020-11-06 21:05:30.351632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1b04d5af14'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('offers', sa.Column('lat', sa.Numeric(), nullable=True))
    op.add_column('offers', sa.Column('lng', sa.Numeric(), nullable=True))
    op.drop_column('offers', 'point_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('point_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('offers', 'lng')
    op.drop_column('offers', 'lat')
    op.drop_column('offers', 'address')
    # ### end Alembic commands ###
