"""length_max modified fields name offer

Revision ID: 9841092249d2
Revises: 872e327d41e6
Create Date: 2020-11-09 18:46:25.684603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9841092249d2'
down_revision = '872e327d41e6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('length_max', sa.Numeric(), nullable=True))
    op.drop_column('offer', 'lenngth_max')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('lenngth_max', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('offer', 'length_max')
    # ### end Alembic commands ###
