"""drop some filds from offer

Revision ID: 872e327d41e6
Revises: 9beaef61c5b6
Create Date: 2020-11-09 17:12:43.034917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872e327d41e6'
down_revision = '9beaef61c5b6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'lead_content')
    op.drop_column('offer', 'mercury_content')
    op.drop_column('offer', 'chromium_content')
    op.drop_column('offer', 'sulphur_content')
    op.drop_column('offer', 'nickel_content')
    op.drop_column('offer', 'copper_content')
    op.drop_column('offer', 'arsenic_content')
    op.drop_column('offer', 'nitrogen_content')
    op.drop_column('offer', 'chlorine_content')
    op.drop_column('offer', 'cadmium_content')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('cadmium_content', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('chlorine_content', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('nitrogen_content', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('arsenic_content', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('copper_content', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('nickel_content', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('sulphur_content', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('chromium_content', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('mercury_content', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('offer', sa.Column('lead_content', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
