def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('search', '/search-results')
    config.add_route('goods', '/table-goods')
    # authentication
    config.add_route('login', '/login')
    config.add_route('logout', '/logout')
    config.add_route('signup', '/signup')
    # points 
    config.add_route('points_at_map', '/points-at-map')
    config.add_route('table_points', '/table-points')
    config.add_route('point', '/point/{id}')
    config.add_route('create_point', '/create-new-point')
    # offers
    config.add_route('view_offer', '/{offer_id}')
    config.add_route('offers_at_map', '/offers-at-map')
    config.add_route('table_offers', '/table-offers')
    config.add_route('create_offer', '/create-offer')
    config.add_route('edit_offer', '/{offer_id}/edit')
    config.add_route('delete_offer', '/{offer_id}/delete')